name: FairyCode
title: FairyCode | Welcome to Seay0's Place !
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
email: ocean1220@naver.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 
paginate: 12
